export type TournamentEvent =
  | 'leaderboard_update'
  | 'round_started'
  | 'round_closed'
  | 'table_assigned'
  | 'result_submitted'
  | 'result_corrected'
  | 'result_confirmed'
  | 'result_disputed'
  | 'result_official'
  | 'stage_advanced'
  | 'dispute_opened'
  | 'dispute_resolved'
  | 'table_dice_roll'
  | 'table_timer_start'
  | 'table_timer_reset'
  | 'table_turn_state';
