export enum TournamentFormat {
  N_ROUNDS_TOP4_FINAL = 'N_ROUNDS_TOP4_FINAL',
  N_ROUNDS_TOP16_SEMIFINAL_FINAL = 'N_ROUNDS_TOP16_SEMIFINAL_FINAL',
  SWISS = 'SWISS',
  GROUPS = 'GROUPS',
  SINGLE_ELIMINATION = 'SINGLE_ELIMINATION',
}
